# Generated by Django 4.2.7 on 2023-11-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resolve_cache',
            field=models.BooleanField(default=False),
        ),
    ]
