# Generated by Django 4.2.7 on 2023-11-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, choices=[('시설', '시설'), ('행정', '행정'), ('복지', '복지'), ('교육', '교육')], max_length=50, null=True),
        ),
    ]
