# Generated by Django 4.2.7 on 2023-11-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='기타', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
