# Generated by Django 4.2.7 on 2023-11-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20231128_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, choices=[('시설', '시설'), ('행정', '행정'), ('복지', '복지'), ('교육', '교육'), ('기타', '기타')], max_length=50, null=True),
        ),
    ]
