# Generated by Django 4.2.7 on 2023-12-01 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20231128_2331'),
        ('post', '0006_tag_post_tags'),
    ]

    operations = [
    ]
