# Generated by Django 4.2.7 on 2023-11-30 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_comment'),
        ('post', '0004_auto_20231128_2331'),
        ('post', '0006_tag_post_tags'),
    ]

    operations = [
    ]
